### ISSUE TITLE
Post y Videos

### ISSUE THREAD

**Issue by ghost** [Mondel/cuentalo#41]
Al comentar un video no deberia redireccionar  a la pagina interna donde se alioja el post es decir comentario/115 porque al hacerlo si alguien comenta el video se le corta la reproduccion y se va a otra pagina y tiene que volver a cargarlo.

**Comment by nmontesdeoca** [comment]
Esto se va a solucionar haciendo que los comentarios sean publicados usando ajax.

**Comment by nmontesdeoca** [comment]
Antes de hacer esto, voy a re organizar y optimizar el javascript. El sitio se esta viendo muy sobrecargado de javascript, un poco lento a veces, y si seguimos agregando funcionalidades con javascript va a ser peor.

**Comment by nmontesdeoca** [comment]
Esta pronto en test para probarlo!.

**Comment by nmontesdeoca** [comment]
Listo en produccion! nadie lo testeó jaja!!!!!!
