### ISSUE TITLE
Boton registrarse

### ISSUE THREAD

**Issue by ghost** [Mondel/cuentalo#43]
Faltaria uno en el menu izquierdo donde esta contactarse y reporte para que la gente se registre mas.

**Comment by nmontesdeoca** [comment]
me parece que poner un boton de registrarse a la izquierda es una locura porque repetiriamos mucho el boton, recorda que esta en todas las paginas en esa barra gris que pusimos, me parece suficiente. vos que decis ?

**Comment by ghost** [comment]
pensandolo lo veo bien lo que decis, se cierra este isue
