### ISSUE TITLE
Nick

### ISSUE THREAD

**Issue by ghost** [Mondel/cuentalo#74]
Llego un pedido de cambio de nick podriamos habilitar decis o sera malo habilitar q lo puedan cambiar? debatimos.

**Comment by nmontesdeoca** [comment]
Si es malo, porque el nick tiene que ser unico para cada usuario, lo que es malo es hacer tantos cambios en el sitio, ya ves que agregamos que se pueda ver el nick y aparecio este caso

**Comment by ghost** [comment]
de acuerdo makinaria!

El 9 de enero de 2012 15:26, nmontesdeoca <
reply@reply.github.com

**Comment by nmontesdeoca** [comment]
Este lo solucionamos por fuera de aca, cuando nos respondan la consulta.

**Comment by ghost** [comment]
Hola:

Faroma te ha invitado a unirte a Facebook.

Después de unirte, podrás conectarte con la página Faroma, junto con otras personas que te importan y otras cosas que te interesan.

Gracias
Faroma

Para registrarte en Facebook, sigue este enlace:
http://www.facebook.com/p.php?i=100000906910302&k=AQDgDAT0kblKGDFKYZSf7AdFqjhmGVjWmaHZkkOiu8iGmACdurFWg_z2YaVgVmisRkD40vBHsh9kYvenClFBqoHTuWM&r&oid=347078012009353

To view the Faroma Page, follow the link below:
http://www.facebook.com/habilitacionesfaroma

Este mensaje se ha enviado a . Si no quieres seguir recibiendo estos mensajes de Facebook, haz clic en el siguiente enlace para eliminar tu nombre de la lista de suscriptores.
http://www.facebook.com/o.php?k=AS3oXBDSbCnikW6C&e=reply%2Bi-2764589-17b52a6bc2fa893e4cb21a328b2b0718af5b758b-1007762%40reply.github.com&mid=HMTA1MTE2ODY3OnJlcGx5K2ktMjc2NDU4OS0xN2I1MmE2YmMyZmE4OTNlNGNiMjFhMzI4YjJiMDcxOGFmNWI3NThiLTEwMDc3NjJAcmVwbHkuZ2l0aHViLmNvbToxMjQ
 Facebook, Inc. Attention: Department 415 P.O Box 10005 Palo Alto CA 94303 

# 

Este mensaje se ha enviado a reply@reply.github.com. Si no quieres seguir recibiendo estos mensajes de Facebook, haz clic en el siguiente enlace para eliminar tu nombre de la lista de suscriptores.
http://www.facebook.com/o.php?k=AS3oXBDSbCnikW6C&e=reply%2Bi-2764589-17b52a6bc2fa893e4cb21a328b2b0718af5b758b-1007762%40reply.github.com&mid=HMTA1MTE2ODY3OnJlcGx5K2ktMjc2NDU4OS0xN2I1MmE2YmMyZmE4OTNlNGNiMjFhMzI4YjJiMDcxOGFmNWI3NThiLTEwMDc3NjJAcmVwbHkuZ2l0aHViLmNvbToxMjQ
 Facebook, Inc. Attention: Department 415 P.O Box 10005 Palo Alto CA 94303
